"""Update wishlist model

Revision ID: b22148097910
Revises: d55abbc9f846
Create Date: 2025-01-20 18:31:17.646873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b22148097910'
down_revision = 'd55abbc9f846'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('place', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('state', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('pincode', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('district', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('city')
        batch_op.drop_column('district')
        batch_op.drop_column('pincode')
        batch_op.drop_column('state')
        batch_op.drop_column('place')
        batch_op.drop_column('customer_name')

    # ### end Alembic commands ###
